### PR TITLE
changes in Readme file

### PR DESCRIPTION
**Pull request by Ava-JeevaYovanE**
I was committing the changes to main because to check whether it ask code review and approval.

### CODE REVIEW

**Review by Ava-Bhagya — APPROVED** [review]
Approved by Bhagya.

**Review by Ava-JeevaYovanE — COMMENTED** [review]
Approved

**Comment by Ava-JeevaYovanE** [comment]
Changes Going to happen in the Readme file which is in **MAIN Branch** and was approved by @Ava-Bhagya

**Comment by Ava-JeevaYovanE** [comment]
Completed the changes

**Pull request merged**
